# Copyright 2024 Vega Cloud, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-agents
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - endpoints
      - events
      - replicationcontrollers    
      - resourcequotas      
      - limitranges       
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apps", "autoscaling", "batch", "extensions"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      - jobs
      - cronjobs
      - horizontalpodautoscalers
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses               
      - networkpolicies
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - services/proxy
      - pods/proxy
      - nodes/proxy
      - nodes/stats
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["external.metrics.k8s.io"]
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - nodes/metrics
      - nodes/stats
      - pods/metrics
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - namespaces/finalizers
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - "get"
      - "list"
      - "watch"


