apiVersion: v1
kind: Secret
metadata:
  name: vega-metrics-agent-secret
  namespace: vegacloud
type: Opaque
stringData:
  VEGA_CLIENT_ID: "{{ .Values.vega.clientId }}"
  VEGA_CLIENT_SECRET: "{{ .Values.vega.clientSecret }}"
