# Copyright 2024 Vega Cloud, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

namespace: vegacloud
serviceAccount:
  name: vega-metrics-sa
image:
  repository: vega-metrics-agent # Do make alldev then push to a private ecr repo to use
  tag: 1.0.1-dev10   # DO A make alldev to build this then push to a private ecr repo to use
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"
securityContext:
  runAsUser: 10000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
vega:
  clientId: ""
  clientSecret: ""
  orgSlug: "vega"
  clusterName: "test-cluster"
env:
  START_COLLECTION_NOW: true
  VEGA_INSECURE: true
