# Copyright 2024 Vega Cloud, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.
namespace: vegacloud
serviceAccount:
  name: vega-metrics-sa
image:
  repository: public.ecr.aws/c0f8b9o4/vegacloud/vega-metrics-agent
  tag: 1.1.1
  pullPolicy: Always
replicaCount: 1
resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"
securityContext:
  runAsUser: 10000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
vega:
  clientId: "XXXXX" # Log into your portal and visit settings->Client Registration to obtain this
  clientSecret: "XXXX" # Log into your portal and visit settings->Client Registration to obtain this
  orgSlug: "XXXX"
  clusterName: "XXXX"
env:
  # For production, you should be using certificates internal to your cluster. 
  # We put this by default becuase most k8s clusters are not using tls certs internally.
  VEGA_INSECURE: true
# VEGA_POLL_INTERVAL: "120m" # Default is 60M
