# Copyright 2024 Vega Cloud, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.
namespace: vegacloud
serviceAccount:
  name: vega-metrics-sa
image:
  repository: public.ecr.aws/c0f8b9o4/vegacloud/vega-metrics-agent
  tag: 1.1.4
  pullPolicy: Always
replicaCount: 1
resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"
securityContext:
  runAsUser: 10000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

# Node selector to constrain pods to specific nodes
nodeSelector: {}
  # Example:
  # disktype: ssd
  # kubernetes.io/os: linux

# Pod affinity/anti-affinity rules
affinity: {}
  # Example:
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - metrics-agent
  #     topologyKey: kubernetes.io/hostname

# Tolerations allow pods to be scheduled on nodes with matching taints
tolerations: []
  # Example:
  # - key: "example-key"
  #   operator: "Exists"
  #   effect: "NoSchedule"

vega:
  clientId: "XXXXX" # Log into your portal and visit settings->Client Registration to obtain this
  clientSecret: "XXXX" # Log into your portal and visit settings->Client Registration to obtain this
  orgSlug: "XXXX"
  clusterName: "XXXX" # This must be a unique identifier for your cluster. may not contain spaces or special characters. regex: ^[-0-9A-Za-z!_.*'\(]+$
env:
  # For production, you should be using certificates internal to your cluster. 
  # We put this by default becuase most k8s clusters are not using tls certs internally.
  VEGA_INSECURE: true
# VEGA_POLL_INTERVAL: "120m" # Default is 60M
