# Copyright 2024 Vega Cloud, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.
# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: vegacloud
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vega-metrics-sa
  namespace: vegacloud
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metrics-agents
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "autoscaling"
    resources:
      - "namespaces"
      - "replicationcontrollers"
      - "services"
      - "nodes"
      - "pods"
      - "jobs"
      - "cronjobs"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "deployments"
      - "replicasets"
      - "daemonsets"
      - "statefulsets"
      - "horizontalpodautoscalers"
    verbs:
      - "get"
      - "watch"
      - "list"
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: metrics-agents
subjects:
  - kind: ServiceAccount
    name: vega-metrics-sa
    namespace: vegacloud
roleRef:
  kind: ClusterRole
  name: metrics-agents
  apiGroup: rbac.authorization.k8s.io
---
# Role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: metrics-agents
  namespace: vegacloud
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - "get"
      - "list"
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: metrics-agents
  namespace: vegacloud
subjects:
  - kind: ServiceAccount
    name: vega-metrics-sa
    namespace: vegacloud
roleRef:
  kind: Role
  name: metrics-agents
  apiGroup: rbac.authorization.k8s.io
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: vega-metrics-agent-secret
  namespace: vegacloud
type: Opaque
stringData:
  VEGA_CLIENT_ID: "XXXXXXXXX"
  VEGA_CLIENT_SECRET: "XXXXXXXXX"
  VEGA_ORG_SLUG: "XXXXXXXXX"
  VEGA_CLUSTER_NAME: "XXXXXXXXX"
---
# Deployment
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vega-metrics-agent
  namespace: vegacloud
  labels:
    app: vega-metrics-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vega-metrics-agent
  template:
    metadata:
      labels:
        app: vega-metrics-agent
    spec:
      serviceAccountName: vega-metrics-sa
      containers:
        - name: vega-metrics-agent
          image: vegacloud/metrics-agent:latest
          imagePullPolicy: Always
          env:
            - name: VEGA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vega-metrics-agent-secret
                  key: VEGA_CLIENT_ID
            - name: VEGA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vega-metrics-agent-secret
                  key: VEGA_CLIENT_SECRET
            - name: VEGA_ORG_SLUG
              valueFrom:
                secretKeyRef:
                  name: vega-metrics-agent-secret
                  key: VEGA_ORG_SLUG
            - name: VEGA_CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: vega-metrics-agent-secret
                  key: VEGA_CLUSTER_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
